import os

# Path consts
PROJECT_ROOT = os.path.dirname(os.path.realpath(__file__))
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')

# Buttons consts
YELLOW_INDEX = 11
ORANGE_INDEX = 16
RED_INDEX = 12
BLUE_INDEX = 14
GREEN_INDEX = 13
PEDAL_INDEX = 15

BUTTONS = [
    YELLOW_INDEX,
    ORANGE_INDEX,
    RED_INDEX,
    BLUE_INDEX,
    GREEN_INDEX,
    PEDAL_INDEX
]

BUTTONS_NAMES = {}
BUTTONS_NAMES[YELLOW_INDEX] = 'yellow'
BUTTONS_NAMES[ORANGE_INDEX] = 'orange'
BUTTONS_NAMES[RED_INDEX] = 'red'
BUTTONS_NAMES[BLUE_INDEX] = 'blue'
BUTTONS_NAMES[GREEN_INDEX] = 'green'
BUTTONS_NAMES[PEDAL_INDEX] = 'pedal'

